# Generated by Django 5.0.7 on 2024-07-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
